remote_theme: LinkedInLearning/jekyll-theme-lil-docs@main
title: Workshop Instructions 
version: false

sidebar:
  - label: Use Codespaces
    children:
      - section-a
      - section-b
      - section-c
  - label: LinkedIn courses
    children:
      - section-a
      - section-b
  - label: Customize Codespaces
    children:
      - section-a
      - section-c


