remote_theme: LinkedInLearning/jekyll-theme-lil-docs@main
title: Workshop Instructions 
version: false

sidebar:
  - welcome
  - label: Manage Codespaces
    children:
      - a-lab-1
      - a-lab-2
      - a-lab-3
      - a-lab-4
      - a-lab-5
      - a-lab-6
      - a-lab-7
      - a-lab-8 
      
  - label: LinkedIn Learning Lessons
    children:
      - b-lab-1
      - b-lab-2
  - label: Customize Codespaces
    children:
      - customizing-01
      - customizing-02
      - customizing-03
      - customizing-04
      - customizing-05
      - customizing-06
  - label: Resources
    children:
      -  linkedin-courses
      -  faq

