remote_theme: LinkedInLearning/jekyll-theme-lil-docs@main
title: Workshop Instructions 
version: false

sidebar:
  - label: Use Codespaces
    children:
      - start-1
      - start-2
      - start-3
      - start-4
      - start-5
  - label: LinkedIn courses
    children:
      - section-a
      - section-b
  - label: Customize Codespaces
    children:
      - section-a
      - section-c
  - resources

