remote_theme: LinkedInLearning/jekyll-theme-lil-docs@main
title: Workshop Instructions 
version: false

sidebar:
  - label: Use Codespaces
    children:
      - start-1
      - start-2
      - start-3
      - start-4
      - start-5
  - label: LinkedIn courses
    children:
      - take-1
      - take-2
  - label: Customize Codespaces
    children:
      - custom-1
      - custom-2
      - custom-3
      - custom-4
  - resources

