remote_theme: LinkedInLearning/jekyll-theme-lil-docs@main
title: Workshop Instructions 
version: false

sidebar:
  - welcome
  - label: Manage Codespaces
    children:
      - a-lab-1
      - a-lab-2
      - a-lab-3
      - a-lab-4
      - a-lab-5
  - label: LinkedIn Learning Lessons
    children:
      - b-lab-1
      - b-lab-2
  - label: Customize Codespaces
    children:
      - c-lab-1
      - c-lab-2
      - c-lab-3
      - c-lab-4
  - resources

