remote_theme: LinkedInLearning/jekyll-theme-lil-docs@main
title: Workshop Instructions 
version: false

sidebar:
  - welcome
  - label: Manage Codespaces
    children:
      - walt-1
      - walt-2
      - walt-3
      - walt-4
      - walt-5
  - label: LinkedIn Learning Lessons
    children:
      - morten-1
      - morten-2
  - label: Customize Codespaces
    children:
      - ray-1
      - ray-2
      - ray-3
      - ray-4
  - resources

